/**
 * Persian labels for print-layout field keys.
 * English keys stay as the stored identifiers; these are display-only.
 */

const partyLabels = (role: "طرف اول" | "طرف دوم") =>
  ({
    name: `نام ${role}`,
    fatherName: `نام پدر ${role}`,
    identityNumber: `شماره شناسنامه ${role}`,
    identityExportPlace: `محل صدور شناسنامه ${role}`,
    nationalCode: `کد ملی ${role}`,
    birthPlace: `محل تولد ${role}`,
    birthDate: `تاریخ تولد ${role}`,
    address: `نشانی ${role}`,
    postalCode: `کد پستی ${role}`,
    phone: `تلفن ${role}`,
  }) as const;

const lawyerLabels = (role: "طرف اول" | "طرف دوم") =>
  ({
    name: `نام وکیل ${role}`,
    fatherName: `نام پدر وکیل ${role}`,
    identityNumber: `شماره شناسنامه وکیل ${role}`,
    birthPlace: `محل تولد وکیل ${role}`,
    birthDate: `تاریخ تولد وکیل ${role}`,
    identityExportPlace: `محل صدور شناسنامه وکیل ${role}`,
    nationalCode: `کد ملی وکیل ${role}`,
    address: `نشانی وکیل ${role}`,
    postalCode: `کد پستی وکیل ${role}`,
    cause: `مورد وکالت ${role}`,
  }) as const;

function flattenParty(
  prefix: "firstParty" | "secondParty",
  role: "طرف اول" | "طرف دوم",
): Record<string, string> {
  const party = partyLabels(role);
  const lawyer = lawyerLabels(role);
  return {
    [`${prefix}.name`]: party.name,
    [`${prefix}.fatherName`]: party.fatherName,
    [`${prefix}.identityNumber`]: party.identityNumber,
    [`${prefix}.identityExportPlace`]: party.identityExportPlace,
    [`${prefix}.nationalCode`]: party.nationalCode,
    [`${prefix}.birthPlace`]: party.birthPlace,
    [`${prefix}.birthDate`]: party.birthDate,
    [`${prefix}.address`]: party.address,
    [`${prefix}.postalCode`]: party.postalCode,
    [`${prefix}.phone`]: party.phone,
    [`${prefix}.lawyer.name`]: lawyer.name,
    [`${prefix}.lawyer.fatherName`]: lawyer.fatherName,
    [`${prefix}.lawyer.identityNumber`]: lawyer.identityNumber,
    [`${prefix}.lawyer.birthPlace`]: lawyer.birthPlace,
    [`${prefix}.lawyer.birthDate`]: lawyer.birthDate,
    [`${prefix}.lawyer.identityExportPlace`]: lawyer.identityExportPlace,
    [`${prefix}.lawyer.nationalCode`]: lawyer.nationalCode,
    [`${prefix}.lawyer.address`]: lawyer.address,
    [`${prefix}.lawyer.postalCode`]: lawyer.postalCode,
    [`${prefix}.lawyer.cause`]: lawyer.cause,
  };
}

export const printFieldLabels: Record<string, string> = {
  ...flattenParty("firstParty", "طرف اول"),
  ...flattenParty("secondParty", "طرف دوم"),

  "organization.name": "نام آژانس / سازمان",
  "organization.licenseNumber": "شماره پروانه / مجوز سازمان",
  "organization.ownerName": "نام مدیر / مالک آژانس",
  "organization.address": "نشانی آژانس",

  "contract.date": "تاریخ قرارداد",
  "contract.time": "ساعت قرارداد",
  "contract.description": "شرح قرارداد",

  "commission.cityRules": "تعرفه اتحادیه / شهر",
  "commission.amount": "مبلغ کمیسیون",
  "commission.firstPartyAmount": "سهم کمیسیون طرف اول",
  "commission.secondPartyAmount": "سهم کمیسیون طرف دوم",
  "commission.taxPercent": "درصد مالیات کمیسیون",
  "commission.amountWithTax": "مبلغ کمیسیون با مالیات",
  "commission.factorNumber": "شماره فاکتور کمیسیون",
  "commission.firstPartyFactorNumber": "شماره فاکتور طرف اول",
  "commission.secondPartyFactorNumber": "شماره فاکتور طرف دوم",

  "property.shareUnits": "دانگ",
  "property.type": "نوع ملک",
  "property.cadastralNumber": "پلاک ثبتی",
  "property.subParcelNumber": "فرعی",
  "property.mainParcelNumber": "اصلی",
  "property.yearBuilt": "سال ساخت",
  "property.cadastralDistrict": "بخش ثبتی",
  "property.registrationArea": "حوزه ثبتی",
  "property.areaSqm": "مساحت (متر مربع)",
  "property.pricePerSqm": "قیمت هر متر مربع",
  "property.parking": "پارکینگ",
  "property.storage": "انباری",
  "property.address": "نشانی ملک",
  "property.postalCode": "کد پستی ملک",
  "property.deedSerialNumber": "شماره سریال سند",
  "property.ownerName": "نام مالک سند",
  "property.bedrooms": "تعداد خواب",
  "property.county": "شهرستان",
  "property.ownershipNumber": "شماره مالکیت",

  "sale.totalAmount": "ثمن کل معامله",
  "sale.totalInWords": "ثمن کل به حروف",
  "sale.prePaymentAmount": "مبلغ بیعانه",
  "sale.prePaymentChequeNumber": "شماره چک بیعانه",
  "sale.prePaymentBankName": "بانک بیعانه",
  "sale.prePaymentBankBranch": "شعبه بانک بیعانه",
  "sale.remainderAmount": "الباقی ثمن",
  "sale.voucherRegistrationDate": "تاریخ تنظیم سند",
  "sale.voucherOrganizationNumber": "شماره دفترخانه / سازمان",
  "sale.deliveryDate": "تاریخ تحویل",
  "sale.cancelationPenalty": "وجه التزام فسخ",
  "sale.breachPenalty": "وجه التزام تخلف",
  "sale.notaryFeePayer": "عهده‌دار هزینه دفترخانه",
  "sale.delayPenaltyFirstPartyPerDay": "وجه التزام تأخیر روزانه طرف اول",
  "sale.delayPenaltySecondPartyPerDay": "وجه التزام تأخیر روزانه طرف دوم",

  "rent.durationMonths": "مدت اجاره (ماه)",
  "rent.fromDate": "از تاریخ",
  "rent.toDate": "تا تاریخ",
  "rent.monthlyAmount": "اجاره ماهانه",
  "rent.monthlyInWords": "اجاره ماهانه به حروف",
  "rent.mortgageAmount": "مبلغ رهن / ودیعه",
  "rent.mortgageInWords": "رهن / ودیعه به حروف",
  "rent.totalInWords": "جمع کل به حروف",
  "rent.prePaymentAmount": "مبلغ پیش‌پرداخت",
  "rent.prePaymentChequeNumber": "شماره چک پیش‌پرداخت",
  "rent.prePaymentBankName": "بانک پیش‌پرداخت",
  "rent.prePaymentBankBranch": "شعبه بانک پیش‌پرداخت",
  "rent.remainderAmount": "الباقی",
  "rent.remainderDueDate": "موعد الباقی",
  "rent.deliveryDate": "تاریخ تحویل",
  "rent.cancelationPenalty": "وجه التزام فسخ",
  "rent.breachPenalty": "وجه التزام تخلف",
  "rent.notaryFeePayer": "عهده‌دار هزینه دفترخانه",
  "rent.delayPenaltyFirstPartyPerDay": "وجه التزام تأخیر روزانه طرف اول",
  "rent.delayPenaltySecondPartyPerDay": "وجه التزام تأخیر روزانه طرف دوم",

  "goodwill.totalAmount": "مبلغ سرقفلی",
  "goodwill.prePaymentAmount": "مبلغ پیش‌پرداخت سرقفلی",
  "goodwill.prePaymentChequeNumber": "شماره چک پیش‌پرداخت",
  "goodwill.prePaymentBankName": "بانک پیش‌پرداخت",
  "goodwill.prePaymentBankBranch": "شعبه بانک پیش‌پرداخت",
  "goodwill.remainderAmount": "الباقی سرقفلی",
  "goodwill.remainderDueDate": "موعد الباقی",
  "goodwill.penaltyAmount": "مبلغ وجه التزام",
  "goodwill.deliveryDate": "تاریخ تحویل",

  "presale.renovationCode": "کد نوسازی",
  "presale.technicalIdNumber": "شناسه فنی",
  "presale.insuranceNumber": "شماره بیمه",
  "presale.buildingPermitNumber": "شماره پروانه ساخت",
  "presale.buildingPermitDate": "تاریخ پروانه ساخت",
  "presale.equipped": "تجهیزات / مجهز بودن",
  "presale.totalFloors": "تعداد طبقات",
  "presale.totalUnits": "تعداد واحدها",
  "presale.areaSqm": "مساحت واحد (متر)",
  "presale.storage": "انباری",
  "presale.orientation": "جهت ملک",
  "presale.parkingNumberAndArea": "شماره و مساحت پارکینگ",
  "presale.flooringType": "نوع کف‌پوش",
  "presale.cabinetAndFaucetType": "نوع کابینت و شیرآلات",
  "presale.bathroomType": "نوع سرویس بهداشتی",
  "presale.switchOutletType": "نوع کلید و پریز",
  "presale.entranceDoorType": "نوع در ورودی",
  "presale.interiorDoorType": "نوع درهای داخلی",
  "presale.ceilingPlasterType": "نوع گچ‌کاری سقف",
  "presale.emergencyWaterSourceType": "منبع آب اضطراری",
  "presale.heatingType": "نوع گرمایش",
  "presale.coolerType": "نوع سرمایش",
  "presale.intercomType": "نوع آیفون",
  "presale.cctv": "دوربین مداربسته",
  "presale.tilingType": "نوع کاشی‌کاری",
  "presale.windowType": "نوع پنجره",
  "presale.facadeType": "نوع نما",
  "presale.parkingFloorWallCover": "پوشش کف و دیوار پارکینگ",
  "presale.lighting": "روشنایی",
  "presale.balconyCorridorRailing": "نرده بالکن / راهرو",
  "presale.fireExtinguisher": "کپسول آتش‌نشانی",
  "presale.elevator": "آسانسور",
  "presale.waterMotor": "موتور آب",
  "presale.utilitiesScore": "امتیاز انشعابات",
  "presale.loan": "وام",
  "presale.loanType": "نوع وام",
  "presale.loanInstallmentAmount": "مبلغ قسط وام",
  "presale.totalAmount": "مبلغ کل پیش‌فروش",
  "presale.totalInWords": "مبلغ کل به حروف",
  "presale.deliveryDate": "تاریخ تحویل",
  "presale.deedTransferDate": "تاریخ انتقال سند",
  "presale.selfDeclareFormNumber": "شماره فرم خوداظهاری",
  "presale.voucherOrganizationNumber": "شماره دفترخانه / سازمان",

  "rescission.originalContractNumber": "شماره قرارداد اصلی",
  "rescission.originalContractDate": "تاریخ قرارداد اصلی",
  "rescission.originalAgencyName": "نام آژانس قرارداد اصلی",
  "rescission.aggregationClause": "بند تجمیع تعهدات",
  "rescission.deliveryClause": "بند تحویل",
  "rescission.price": "مبلغ تسویه / فسخ",
  "rescission.paymentType": "نحوه پرداخت تسویه",

  "cjv.propertyDescription": "شرح ملک / زمین",
  "cjv.totalAmount": "مبلغ کل مشارکت",
  "cjv.totalInWords": "مبلغ کل به حروف",
  "cjv.governmentalCosts": "هزینه‌های دولتی",
  "cjv.constructionCosts": "هزینه‌های ساخت",
  "cjv.facilityRightsCosts": "هزینه حق انشعاب / تسهیلات",
  "cjv.destructionCost": "هزینه تخریب",
  "cjv.firstPartyShare": "سهم طرف اول",
  "cjv.secondPartyShare": "سهم طرف دوم",
  "cjv.startDateInWords": "تاریخ شروع به حروف",
  "cjv.endDateInWords": "تاریخ پایان به حروف",
  "cjv.costDetailsPrepareDate": "تاریخ تهیه جزئیات هزینه",
  "cjv.voucherTransferDate": "تاریخ انتقال سند / وکالت",
  "cjv.shareUnitsToTransfer": "دانگ قابل انتقال",
  "cjv.delayPenaltyFirstPartyPerDay": "وجه التزام تأخیر روزانه طرف اول",
  "cjv.delayPenaltySecondPartyPerDay": "وجه التزام تأخیر روزانه طرف دوم",
};

export function printFieldLabel(key: string): string {
  return printFieldLabels[key] ?? key;
}
