import type { ContractType } from "@/lib/api/types";
import {
  partyFieldsForContract,
  partyPrintKeysFromFields,
  propertyFieldsForContract,
  propertyPrintKeysFromFields,
} from "@/lib/contracts/contract-entity-fields";

const lawyerKeys = (prefix: "firstParty" | "secondParty") =>
  [
    `${prefix}.lawyer.name`,
    `${prefix}.lawyer.fatherName`,
    `${prefix}.lawyer.identityNumber`,
    `${prefix}.lawyer.birthPlace`,
    `${prefix}.lawyer.birthDate`,
    `${prefix}.lawyer.identityExportPlace`,
    `${prefix}.lawyer.nationalCode`,
    `${prefix}.lawyer.address`,
    `${prefix}.lawyer.postalCode`,
    `${prefix}.lawyer.cause`,
  ] as const;

const orgStampKeys = [
  "organization.name",
  "organization.licenseNumber",
  "organization.ownerName",
  "organization.address",
  "contract.date",
  "contract.time",
  "contract.description",
  "commission.cityRules",
  "commission.amount",
  "commission.firstPartyAmount",
  "commission.secondPartyAmount",
  "commission.taxPercent",
  "commission.amountWithTax",
  "commission.factorNumber",
  "commission.firstPartyFactorNumber",
  "commission.secondPartyFactorNumber",
] as const;

/** Terms-only property keys that are not derived from PropertyForm fields. */
const PROPERTY_TERMS_ONLY: Record<ContractType, readonly string[]> = {
  SALE: ["property.shareUnits", "property.pricePerSqm"],
  RENT: ["property.shareUnits", "property.ownerName"],
  GOODWILL: ["property.shareUnits", "property.pricePerSqm"],
  PRE_SALE: [],
  MUTUAL_RESCISSION: [
    "property.shareUnits",
    "property.county",
    "property.ownershipNumber",
  ],
  CONSTRUCTION_JOINT_VENTURE: ["property.shareUnits"],
};

const TYPE_TERMS_KEYS: Record<ContractType, readonly string[]> = {
  SALE: [
    "sale.totalAmount",
    "sale.totalInWords",
    "sale.prePaymentAmount",
    "sale.prePaymentChequeNumber",
    "sale.prePaymentBankName",
    "sale.prePaymentBankBranch",
    "sale.remainderAmount",
    "sale.voucherRegistrationDate",
    "sale.voucherOrganizationNumber",
    "sale.deliveryDate",
    "sale.cancelationPenalty",
    "sale.breachPenalty",
    "sale.notaryFeePayer",
    "sale.delayPenaltyFirstPartyPerDay",
    "sale.delayPenaltySecondPartyPerDay",
  ],
  RENT: [
    "rent.durationMonths",
    "rent.fromDate",
    "rent.toDate",
    "rent.monthlyAmount",
    "rent.monthlyInWords",
    "rent.mortgageAmount",
    "rent.mortgageInWords",
    "rent.totalInWords",
    "rent.prePaymentAmount",
    "rent.prePaymentChequeNumber",
    "rent.prePaymentBankName",
    "rent.prePaymentBankBranch",
    "rent.remainderAmount",
    "rent.remainderDueDate",
    "rent.deliveryDate",
    "rent.cancelationPenalty",
    "rent.breachPenalty",
    "rent.notaryFeePayer",
    "rent.delayPenaltyFirstPartyPerDay",
    "rent.delayPenaltySecondPartyPerDay",
  ],
  GOODWILL: [
    "goodwill.totalAmount",
    "goodwill.prePaymentAmount",
    "goodwill.prePaymentChequeNumber",
    "goodwill.prePaymentBankName",
    "goodwill.prePaymentBankBranch",
    "goodwill.remainderAmount",
    "goodwill.remainderDueDate",
    "goodwill.penaltyAmount",
    "goodwill.deliveryDate",
  ],
  PRE_SALE: [
    "presale.renovationCode",
    "presale.technicalIdNumber",
    "presale.insuranceNumber",
    "presale.buildingPermitNumber",
    "presale.buildingPermitDate",
    "presale.equipped",
    "presale.totalFloors",
    "presale.totalUnits",
    "presale.areaSqm",
    "presale.storage",
    "presale.orientation",
    "presale.parkingNumberAndArea",
    "presale.flooringType",
    "presale.cabinetAndFaucetType",
    "presale.bathroomType",
    "presale.switchOutletType",
    "presale.entranceDoorType",
    "presale.interiorDoorType",
    "presale.ceilingPlasterType",
    "presale.emergencyWaterSourceType",
    "presale.heatingType",
    "presale.coolerType",
    "presale.intercomType",
    "presale.cctv",
    "presale.tilingType",
    "presale.windowType",
    "presale.facadeType",
    "presale.parkingFloorWallCover",
    "presale.lighting",
    "presale.balconyCorridorRailing",
    "presale.fireExtinguisher",
    "presale.elevator",
    "presale.waterMotor",
    "presale.utilitiesScore",
    "presale.loan",
    "presale.loanType",
    "presale.loanInstallmentAmount",
    "presale.totalAmount",
    "presale.totalInWords",
    "presale.deliveryDate",
    "presale.deedTransferDate",
    "presale.selfDeclareFormNumber",
    "presale.voucherOrganizationNumber",
  ],
  MUTUAL_RESCISSION: [
    "rescission.originalContractNumber",
    "rescission.originalContractDate",
    "rescission.originalAgencyName",
    "rescission.aggregationClause",
    "rescission.deliveryClause",
    "rescission.price",
    "rescission.paymentType",
  ],
  CONSTRUCTION_JOINT_VENTURE: [
    "cjv.propertyDescription",
    "cjv.totalAmount",
    "cjv.totalInWords",
    "cjv.governmentalCosts",
    "cjv.constructionCosts",
    "cjv.facilityRightsCosts",
    "cjv.destructionCost",
    "cjv.firstPartyShare",
    "cjv.secondPartyShare",
    "cjv.startDateInWords",
    "cjv.endDateInWords",
    "cjv.costDetailsPrepareDate",
    "cjv.voucherTransferDate",
    "cjv.shareUnitsToTransfer",
    "cjv.delayPenaltyFirstPartyPerDay",
    "cjv.delayPenaltySecondPartyPerDay",
  ],
};

function catalogForType(type: ContractType): readonly string[] {
  return [
    ...partyPrintKeysFromFields(partyFieldsForContract(type), "firstParty"),
    ...lawyerKeys("firstParty"),
    ...partyPrintKeysFromFields(partyFieldsForContract(type), "secondParty"),
    ...lawyerKeys("secondParty"),
    ...propertyPrintKeysFromFields(propertyFieldsForContract(type)),
    ...PROPERTY_TERMS_ONLY[type],
    ...TYPE_TERMS_KEYS[type],
    ...orgStampKeys,
  ];
}

/** Allowed overlay field keys per contract type (aligned with entity form fields). */
export const PRINT_FIELD_CATALOG: Record<ContractType, readonly string[]> = {
  SALE: catalogForType("SALE"),
  RENT: catalogForType("RENT"),
  GOODWILL: catalogForType("GOODWILL"),
  PRE_SALE: catalogForType("PRE_SALE"),
  MUTUAL_RESCISSION: catalogForType("MUTUAL_RESCISSION"),
  CONSTRUCTION_JOINT_VENTURE: catalogForType("CONSTRUCTION_JOINT_VENTURE"),
};

export function catalogKeysForType(type: ContractType): readonly string[] {
  return PRINT_FIELD_CATALOG[type];
}
